### ISSUE TITLE
Item Alchemy Fuel 1.21

### ISSUE THREAD

**Issue by SveezZ** [Pitan76/item-alchemy#115] opened 2024-08-15 21:07 UTC
I seem to have a problem with the Alchemical, Mobius, and Aeternalis Fuel. Whenever I try to craft alchemical fuel it doesn't work, and I was hoping you could help me try and resolve this issue? Also the Philosopher's Stone still shows the durability bar even after it wont allow me to press "v" anymore,

**Comment by tehbasshunter** [comment] 2024-09-10 10:28
Fuel is fixed with 0.9.1 update for Item Alchemy and 2.4.0-1.21 of MCPitanLib.

**Comment by PTOM76** [comment] 2024-09-12 09:13
The health bar is displayed by design.

**Closed** 2024-09-12 09:13 UTC
